---
name: ci
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: fkautz/shell-linter@v1.0.1
