---
name: ci
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/glazychev-art/test-repo/actions/runners/registration-token
      - name: Setup envs
        run: |
          echo "github.repository ${{ github.repository }}"
          echo "github.event.workflow_run.conclusion ${{ github.event.workflow_run.conclusion }}"
          echo "github.event_name ${{ github.event_name }}"
          echo "github.actor ${{ github.actor }}"
          echo "github.ref ${{ github.ref }}"
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: fkautz/shell-linter@v1.0.1
